site_name: Tywrap Studios Doc hub
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: pink
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: pink
  logo: assets/Main_Transparent.png
  favicon: assets/favicon.ico
  features:
    - content.tabs.link
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
copyright: Copyright &copy; 2025 Tywrap Studios
