authors:
  tiazzz:
    name: ItsTiazzz
    description: Founder, Developer
    avatar: https://avatars.githubusercontent.com/u/163735662?v=4
    url: https://tiazzz.me/home
  stendeston:
    name: StendeSton
    description: Co-Owner, Developer, Certified Cat
    avatar: assets/Main_Transparent.png